### ISSUE TITLE
Gem name

### ISSUE THREAD

**Issue by baldwindavid** [Sutto/slugged#1]
Simple slug library...complex name!  How about just "slugged"?  It has not been taken.

**Comment by Sutto** [comment]
I like this idea and am working on switching it over right now - cheers!

**Comment by Sutto** [comment]
Hi baldwindavid, thanks for the awesome name - This was the most requested feature from all the people who I'd shown the library - It's now officially known as slugged.

Cheers!

**Comment by baldwindavid** [comment]
Great!  I'm glad you like it.
