### ISSUE TITLE
undefined method "is_sluggable "

### ISSUE THREAD

**Issue by amoslanka** [Sutto/slugged#2]
Having a little trouble on the home stretch of using this plugin. Would really love to get all in place, I like what I see in this plugin.

After getting gem installed and migrations all in place, the is_sluggable, when placed in a model, is throwing an error stating its undefined. 

Not sure I understand why the method wouldn't be defined. I've followed the readme as close as possible. Has anyone come across this before?

**Comment by Sutto** [comment]
I'm assuming by Gem installed you mean that you placed it in your Gemfile / required it somewhere else as well?

The issue is most likely that the ar extensions aren't being loaded - open up IRB and check the results of "defined?(Slugged)" and then check "defined?(Slugged::ActiveRecordMethods)".

**Comment by amoslanka** [comment]
Sorry for the late reply. This issue is resolved for me. It can be closed.

**Comment by eemi** [comment]
I have the same problem (I get undefined method "is_sluggable"), in the console the output for defined?(Slugged) and defined?(Slugged::ActiveRecordMethods) is "constant".

I'm fairly new to Rails and I dont know if getting constant is a good or a bad thing!

**Comment by eemi** [comment]
Sorry. After restarting the server the problem is gone.
